version: "3.1"
services:
  reportprovidermove:
    build: ../../KheopsReportProvider
    # TODO: Change 'viewer' with eg 'move'
    # image: osirixfoundation/kheops-report-provider:viewer
    container_name: reportprovidermove
    env_file: docker-compose.env
    restart: always
    extra_hosts:
      - "demo.kheops.online:10.5.7.30"
      - "test.kheops.online:10.5.7.30"
      - "lavim.kheops.online:10.5.7.30"
      - "lavim.unige.ch:10.5.7.30"
      - "aneux.kheops.online:10.5.7.30"
    networks:
      - reportprovidermove-network
    secrets:
      - privkey.pem

  nginx:
    image: nginx:1.21-alpine
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginxconf:/etc/nginx/
    depends_on:
      - reportprovidermove
    networks:
      - reportprovidermove-network

secrets:
  privkey.pem:
    file: secrets/privkey.pem

networks:
  reportprovidermove-network:
    driver: bridge
    ipam:
      driver: default
      config:
#       TODO: Change this subnet?
        - subnet: "172.20.100.0/24"
