version: "3.1"
services:
  reportprovider:
    image: osirixfoundation/kheops-report-provider:cookie-secure
    container_name: reportprovider
    env_file: docker-compose.env
    restart: always
    secrets:
      - privkey.pem

  nginx:
    image: nginx:1.14-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginxconf:/etc/nginx/
    depends_on:
      - reportprovider
    secrets:
      - privkey1.pem
      - fullchain1.pem

secrets:
  privkey1.pem:
    file: secrets/privkey1.pem
  fullchain1.pem:
    file: secrets/fullchain1.pem
  privkey.pem:
    file: secrets/privkey.pem
