version: "3.1"
services:
  reportprovider:
    image: osirixfoundation/kheops-report-provider:viewer
    container_name: reportprovider
    env_file: docker-compose.env
    restart: always
    extra_hosts:
      - "demo.kheops.online:10.5.5.31"
      - "test2.kheops.online:10.5.5.28"
      - "test.kheops.online:10.5.5.27"
      - "lavim.kheops.online:10.5.7.3"
      - "lavim.unige.ch:10.5.7.3"
      - "aneux.kheops.online:10.5.7.9"
    secrets:
      - privkey.pem
    networks:
      - reportprovider-network

  nginx:
    image: nginx:1.18-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginxconf:/etc/nginx/
    depends_on:
      - reportprovider
    secrets:
      - privkey1.pem
      - fullchain1.pem
    networks:
      - reportprovider-network

secrets:
  privkey1.pem:
    file: secrets/privkey1.pem
  fullchain1.pem:
    file: secrets/fullchain1.pem
  privkey.pem:
    file: secrets/privkey.pem

networks:
  reportprovider-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.100.0/24"
