version: "3.1"
services:
  reportprovider:
    image: osirixfoundation/kheops-report-provider:master
    container_name: reportprovider
    env_file: docker-compose.env
    restart: always
    extra_hosts:
      - "demo.kheops.online:10.5.5.32"
      - "test2.kheops.online:10.5.5.28"
      - "test.kheops.online:10.5.5.27"
      - "lavim.kheops.online:10.5.7.3"
      - "aneux.kheops.online:10.5.7.9"

    secrets:
      - privkey.pem

  nginx:
    image: nginx:1.14-alpine
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginxconf:/etc/nginx/
    depends_on:
      - reportprovider
